services:
  postgres:
    image: postgres:16
    container_name: jmip-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jmip
    ports:
      - "5432:5432"
    volumes:
      - jmip_pgdata:/var/lib/postgresql/data

volumes:
  jmip_pgdata: